networks:
    backend:
        driver: bridge
volumes:
    db-data:
services:
    api:
        build: ./api
        depends_on:
            database:
                condition: service_healthy
        environment:
            - ASPNETCORE_HTTPS_PORT=443
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_PORT=${MYSQL_DB_PORT}
            - MYSQL_DB_DATABASE=${MYSQL_DB_DATABASE}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
        ports:
            - 5000:80
        networks:
            - backend
    database:
        build: ./database
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 5s
            timeout: 3s
            retries: 10
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
            - MYSQL_USER=${MYSQL_DB_USER}
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - backend