networks:
    front-tier:
        driver: bridge
    back-tier:
        driver: bridge

services:
    api:
        build: ./api
        environment:
            - ASPNETCORE_HTTPS_PORT=443
        ports:
            - 5000:80
        networks:
            - front-tier
            - back-tier
    database:
        build: ./database
        environment:
            - MARIADB_AUTO_UPGRADE=1
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./database/data:/var/lib/mysql
        networks:
            - back-tier