networks:
    front-tier:
        driver:
            bridge
    back-tier:
        driver: bridge

volumes:
    db-data:

services:
    api:
        build: ./mes-poc-dotnet-app
        depends_on:
            database:
                condition: service_healthy
        environment:
            - MYSQL_HOST=${MYSQL_DB_HOST}
            - MYSQL_PORT=${MYSQL_DB_PORT}
            - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
            - MYSQL_USER=${MYSQL_DB_USER}
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
        ports:
            - 5000:80
            - 5001:443
        networks:
            - front-tier
            - back-tier
        labels:
            kompose.service.type: LoadBalancer

    database:
        build: ./mes-poc-database
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 5s
            timeout: 3s
            retries: 10
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
            - MYSQL_USER=${MYSQL_DB_USER}
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_PORT=3306
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - back-tier
    
    rabbit-mq:
        image: rabbitmq:3-management        
        ports:
            - 8080:15672
        environment:
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        networks:
            - back-tier
